[package]
name = "rust_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.21.0", features = [ "derive" ] }
env_logger = "0.11.6"
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.8"
